[package]
name = "termai"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rusqlite = { version = "0.32", features = ["bundled"] }
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
reqwest = { version = "0.12.8", features = ["json"] }
colored = "2.1.0"
syntect = "5.0"
tempfile = "3.13.0"
dirs = "5.0.1"
regex = "1.11.0"

